# Generated by Django 2.0.5 on 2022-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Баннер магазина'),
        ),
    ]
