# Generated by Django 2.0.5 on 2022-05-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220523_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(blank=True, default='Null', upload_to='photos', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, default='Null', upload_to='photos', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, default='Null', upload_to='photos', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, default='Null', upload_to='photos', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, default='Null', upload_to='photos', verbose_name='Баннер магазина'),
        ),
    ]
